version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 140023408041.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t flask-app .
      - docker tag flask-app:latest 140023408041.dkr.ecr.ap-south-1.amazonaws.com/flask-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 140023408041.dkr.ecr.ap-south-1.amazonaws.com/flask-app:latest
      - echo Deploying to EKS...
      - kubectl apply -f eks-deployment/deployment.yaml
      - kubectl apply -f eks-deployment/service.yaml

artifacts:
  files:
    - eks-deployment/*.yaml
